### ISSUE TITLE
URLs not available for "LoadData"

### ISSUE THREAD

**Issue by mteleman** [stevexniu/spots#1]
Hi !
First, thanks for your amazing work. It's a really interesting package.
To get back to the issue, when I use both function "LoadData" & "VisiumHnn", I always get the error:

`trying URL 'https://drive.google.com/uc?export=download&id=1bLZfqTTzkbBTGYdr8lzct8CHDKtHGfEl'
Warning: cannot open URL 'https://drive.google.com/uc?export=download&id=1bLZfqTTzkbBTGYdr8lzct8CHDKtHGfEl': HTTP status was '404 Not Found'Error in download.file(url = meta.data[["url"]], destfile = file.path) : 
  cannot open URL 'https://drive.google.com/uc?export=download&id=1bLZfqTTzkbBTGYdr8lzct8CHDKtHGfEl'`

And indeed, when I manually try to go to the urls, I also get the 404 error.

The datasets are not available anymore ?

Thank you in advance for your time and help.

Best regards.

**Comment by stevexniu** [comment]
Thanks, @mteleman!

The links were disabled by our account administrator. I will find a permanent fix for that.
Here is a quick fix, the R objects are re-shared: [Visium.hnn.dist.rds](https://drive.google.com/uc?export=download&id=1YqnvInZxxNuZU7KFg6LGTOEN2Ya3D88q) and [Visium.brain.rds](https://drive.google.com/uc?export=download&id=14K2Y16b2iuaEwF992jU9A7IBiUP_w7h-)

**Comment by mteleman** [comment]
Thank you very much !

**Comment by Starsm7** [comment]
> Thanks, @mteleman!
> 
> The links were disabled by our account administrator. I will find a permanent fix for that. Here is a quick fix, the R objects are re-shared: [Visium.hnn.dist.rds](https://drive.google.com/uc?export=download&id=1YqnvInZxxNuZU7KFg6LGTOEN2Ya3D88q) and [Visium.brain.rds](https://drive.google.com/uc?export=download&id=14K2Y16b2iuaEwF992jU9A7IBiUP_w7h-)

Thank you！I've wasted a lot of time searching for this
